use crate::types::{Motion, RectSplit};

#[derive(Clone, PartialEq, Eq)]
pub enum Command {
    Move(Motion),
    Delete(Motion),
    DeleteLine,
    Change(Motion),
    ChangeLine,
    Yank(Motion),
    YankLine,
    ScrollView(Motion),
    Undo,
    HotRedo,
    Append,
    AppendEndOfLine,
    InsertLineBelow,
    InsertLineAbove,
    SwapLineDown,
    SwapLineUp,
    Indent,
    Dedent,
    Paste,
    DeleteChar,
    Replace,
    ReplaceChar(char),
    SaveFile,
    Jump,
    SplitWindow(RectSplit),
    FocusWindow(Motion),
    EnterInsertMode,
    EnterVisualMode,
    EnterSearchMode,
    EnterDirMode,
    Quit,
}
